### ISSUE TITLE
f8 roadmap 

### ISSUE THREAD

**Issue by luckyufei** [allanfish/f8#1]
## version：0.1.0 ,  deadtime: 2016.08.31
- [ ] 改造jmui中的文档, 保持和f7的文档一致, 方便补全组件
- [ ] 将f8中缺失的f7的组件一一补全
- [ ] 在阿里云上部署f8的官网
- [ ] 模范amazeui-react的文档方式, 用户可以直接在线编辑组件,实时查看编辑效果

**Comment by luckyufei** [comment]
为什么要同步文档? 

因为我们的f8是基于f7和jmui开发的, 而jmui的文档非常不全面,  所以希望可以吧f7中的文档完全迁移到f8中来.  保证每个示例都覆盖到了所有的情况. 

具体做法是: 比较[jmui](https://junewinds.github.io/jmui/)和[f7](http://framework7.io/kitchen-sink-ios/)中各个组件文档的不同, 以f7为标准, 在f8中实现. 

@soakit
